# fly.toml app configuration file generated for poke-discord-bot-dappled-sky-5062 on 2026-06-22T22:31:40+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poke-discord-bot-dappled-sky-5062'
primary_region = 'nrt'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
